// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbveluprkmphtuxfvpha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtidmVsdXBya21waHR1eGZ2cGhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk1MTc2NzksImV4cCI6MjA3NTA5MzY3OX0.FU74MR6adBlYi2EK8rAUnnC3pXQM-Wspp3ucof2eFSE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});